env:
  es2022: true
  node: true
extends:
- eslint:recommended
parserOptions:
  sourceType: module
  project:
  - "./tsconfig.json"
  - "./test/tsconfig.json"
rules:
  no-console:
  - error
  indent:
  - error
  - 4
  - FunctionDeclaration:
      parameters: 1
    FunctionExpression:
      parameters: 1
    SwitchCase: 1
  max-len:
  - warn
  - code: 120
    ignoreUrls: true
overrides:
  - files: ["*.ts", "*.tsc"]
    extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
    parser: "@typescript-eslint/parser"
    plugins:
    - "@typescript-eslint"
    rules:
      "@typescript-eslint/ban-types":
      - error
      - types:
          Function: false
      "@typescript-eslint/explicit-module-boundary-types":
      - error
      - allowArgumentsExplicitlyTypedAsAny: true
      "@typescript-eslint/naming-convention":
      - error
      - selector: interface
        format:
        - PascalCase
        custom:
          regex: "^I[A-Z]"
          match: true
      "@typescript-eslint/no-explicit-any":
      - 'off'
      "@typescript-eslint/no-misused-promises":
      - error
      - checksVoidReturn: false
      "@typescript-eslint/no-unused-vars":
      - error
      - argsIgnorePattern: "^_[0-9A-Za-z]*$"
      "@typescript-eslint/semi":
      - error
      "@typescript-eslint/unbound-method":
      - off
